#!/usr/bin/env ruby
require_relative 'lib/config/file'
require_relative 'lib/state/file'
require_relative 'lib/infrastructure_change_planner'
require_relative 'lib/tunnel_planner'

config = Rook::Config::File.load_file("Rookfile")
state = Rook::State::File.load_file("Rookfile.state")
state.write(STDOUT)

# planner = Rook::InfrastructureChangePlanner.new(
#   :config => config,
#   :state => state)
# planner.run

planner = Rook::TunnelPlanner.new(:config => config, :state => state)
planner.run

state.write(STDOUT)
