#!/usr/bin/env ruby
require_relative 'lib/config/file'
require_relative 'lib/state/file'
require_relative 'lib/host_provisioners/dummy'
require_relative 'lib/container_provisioners/dummy'

state = Rook::State::File.load_file("Rookfile.state")
state.write(STDOUT)

config = Rook::Config::File.load_file("Rookfile")
