#!/usr/bin/env ruby
require_relative 'lib/config/file'
require_relative 'lib/state/file'
require_relative 'lib/planners/infrastructure_change_planner'
require_relative 'lib/planners/route_planner'

logger = Rook.default_logger
config = Rook::Config::File.load_file("Rookfile")
state = Rook::State::File.load_file("Rookfile.state")
state.write(STDOUT)

logger.info "Making a plan for necessary infrastructure changes"
planner = Rook::InfrastructureChangePlanner.new(
  :config => config,
  :state => state)
if !planner.run
  logger.info "No infrastructure changes necessary"
end

logger.info "Making a plan for routes"
planner = Rook::RoutePlanner.new(:config => config, :state => state)
planner.run

state.write(STDOUT)
